# Generated by Django 4.2.30 on 2026-07-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
